import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const InvoiceCustomerInfo = ({ invoice }) => {
    return (_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-8 mb-8", children: [_jsxs("div", { className: "bg-white/80 backdrop-blur-sm rounded-2xl p-6 border border-heritage-neutral/20 shadow-sm", children: [_jsxs("h3", { className: "text-lg font-bold text-heritage-green mb-4 flex items-center gap-2", children: [_jsx("svg", { className: "w-5 h-5", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" }) }), "Guest Information"] }), _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { children: [_jsx("span", { className: "text-sm font-medium text-heritage-neutral/70", children: "Full Name" }), _jsx("p", { className: "text-base font-semibold text-heritage-green", children: invoice.guestName })] }), _jsxs("div", { children: [_jsx("span", { className: "text-sm font-medium text-heritage-neutral/70", children: "Room Number" }), _jsxs("p", { className: "text-base font-semibold text-heritage-green", children: ["Room ", invoice.roomNumber] })] }), _jsxs("div", { children: [_jsx("span", { className: "text-sm font-medium text-heritage-neutral/70", children: "Guest Type" }), _jsx("p", { className: "text-base font-semibold text-heritage-green", children: "Premium Guest" })] })] })] }), _jsxs("div", { className: "bg-white/80 backdrop-blur-sm rounded-2xl p-6 border border-heritage-neutral/20 shadow-sm", children: [_jsxs("h3", { className: "text-lg font-bold text-heritage-green mb-4 flex items-center gap-2", children: [_jsx("svg", { className: "w-5 h-5", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" }) }), "Stay Information"] }), _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { children: [_jsx("span", { className: "text-sm font-medium text-heritage-neutral/70", children: "Check-in Date" }), _jsx("p", { className: "text-base font-semibold text-heritage-green", children: invoice.checkIn })] }), _jsxs("div", { children: [_jsx("span", { className: "text-sm font-medium text-heritage-neutral/70", children: "Check-out Date" }), _jsx("p", { className: "text-base font-semibold text-heritage-green", children: invoice.checkOut })] }), _jsxs("div", { children: [_jsx("span", { className: "text-sm font-medium text-heritage-neutral/70", children: "Payment Status" }), _jsxs("span", { className: `inline-flex items-center px-3 py-1 rounded-full text-sm font-semibold ${invoice.status === 'paid'
                                            ? 'bg-emerald-100 text-emerald-800 border border-emerald-200'
                                            : invoice.status === 'pending'
                                                ? 'bg-amber-100 text-amber-800 border border-amber-200'
                                                : 'bg-red-100 text-red-800 border border-red-200'}`, children: [_jsx("div", { className: `w-2 h-2 rounded-full mr-2 ${invoice.status === 'paid' ? 'bg-emerald-500' :
                                                    invoice.status === 'pending' ? 'bg-amber-500' : 'bg-red-500'}` }), invoice.status.charAt(0).toUpperCase() + invoice.status.slice(1)] })] })] })] })] }));
};
export default InvoiceCustomerInfo;
