import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Users } from 'lucide-react';
export const DepartmentCards = ({ departmentProfits }) => {
    const formatCurrency = (amount) => {
        return new Intl.NumberFormat('en-PH', {
            style: 'currency',
            currency: 'PHP',
            minimumFractionDigits: 0,
            maximumFractionDigits: 0,
        }).format(amount);
    };
    return (_jsxs("div", { className: "lg:col-span-2 relative overflow-hidden bg-white/95 backdrop-blur-xl rounded-3xl shadow-2xl border border-white/60", children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-br from-heritage-green/5 via-heritage-light/10 to-heritage-green/5 rounded-3xl opacity-50" }), _jsxs("div", { className: "relative z-10 p-8", children: [_jsxs("div", { className: "flex items-center space-x-5", children: [_jsxs("div", { className: "relative group", children: [_jsx("div", { className: "p-2 bg-[#82A33D]/10 rounded-xl", children: _jsx(Users, { className: "w-6 h-6 text-[#82A33D]" }) }), _jsx("div", { className: "absolute -inset-2 rounded-2xl blur-xl opacity-60 group-hover:opacity-100 transition-opacity duration-300 bg-gradient-to-r from-heritage-green/20 to-heritage-neutral/20" })] }), _jsxs("div", { children: [_jsx("h3", { className: "text-2xl font-black text-transparent bg-gradient-to-r from-gray-900 via-gray-800 to-gray-900 bg-clip-text", children: "Department Performance" }), _jsxs("div", { className: "flex items-center gap-2 mt-1", children: [_jsx("p", { className: "text-sm font-semibold text-gray-600", children: "Revenue and profitability overview" }), _jsx("div", { className: "w-1 h-1 rounded-full bg-heritage-green" }), _jsx("span", { className: "text-sm font-bold text-heritage-green", children: "November 2025" })] })] })] }), _jsx("div", { className: "grid grid-cols-2 gap-4", children: departmentProfits && departmentProfits.length > 0 ? (departmentProfits.map((dept, index) => (_jsxs("div", { className: "group relative overflow-hidden bg-white/60 backdrop-blur-sm p-5 rounded-2xl border border-gray-200/60 hover:border-heritage-green/40 hover:shadow-xl hover:-translate-y-1 transition-all duration-300 animate-fade-in", style: { animationDelay: `${index * 100}ms` }, children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-br from-heritage-green/0 to-heritage-green/5 opacity-0 group-hover:opacity-100 transition-opacity duration-300 rounded-2xl" }), _jsxs("div", { className: "relative z-10", children: [_jsxs("div", { className: "flex items-center justify-between mb-4", children: [_jsxs("div", { className: "flex items-center space-x-3", children: [_jsxs("div", { className: `relative w-10 h-10 rounded-xl flex items-center justify-center text-xl shadow-md group-hover:scale-110 transition-transform duration-300 ${dept.department === 'Rooms' ? 'bg-gradient-to-br from-teal-400 to-teal-600' :
                                                                dept.department === 'Food & Beverage' ? 'bg-gradient-to-br from-orange-400 to-orange-600' :
                                                                    dept.department === 'Events' ? 'bg-gradient-to-br from-amber-400 to-amber-600' :
                                                                        'bg-gradient-to-br from-red-400 to-red-600'}`, children: [dept.department === 'Rooms' ? '🏨' :
                                                                    dept.department === 'Food & Beverage' ? '🍽️' :
                                                                        dept.department === 'Events' ? '🎉' : '⚡', _jsx("div", { className: "absolute -inset-0.5 bg-gradient-to-br from-white/20 to-transparent rounded-xl" })] }), _jsxs("div", { children: [_jsx("p", { className: "font-black text-gray-900 text-sm group-hover:text-heritage-green transition-colors", children: dept.department }), _jsx("p", { className: "text-xs text-gray-500 font-medium", children: "Department" })] })] }), _jsx("span", { className: `text-xs font-bold px-3 py-1 rounded-full shadow-sm ${dept.status === 'excellent' ? 'bg-emerald-100 text-emerald-700' :
                                                        dept.status === 'good' ? 'bg-blue-100 text-blue-700' :
                                                            dept.status === 'poor' ? 'bg-orange-100 text-orange-700' :
                                                                'bg-red-100 text-red-700'}`, children: dept.status.toUpperCase() })] }), _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { className: "flex justify-between items-center", children: [_jsx("span", { className: "text-sm font-semibold text-gray-600", children: "Revenue" }), _jsx("span", { className: "text-base font-bold text-gray-900", children: formatCurrency(dept.revenue) })] }), _jsxs("div", { className: "flex justify-between items-center", children: [_jsx("span", { className: "text-sm font-semibold text-gray-600", children: "Profit" }), _jsxs("span", { className: `text-base font-black ${dept.profit > 0 ? 'text-emerald-600' : 'text-red-600'}`, children: [dept.profit > 0 ? '+' : '-', formatCurrency(Math.abs(dept.profit))] })] }), _jsx("div", { className: "pt-3 border-t border-gray-200/60", children: _jsxs("div", { className: "flex justify-between items-center", children: [_jsx("span", { className: "text-sm font-semibold text-gray-600", children: "Margin" }), _jsxs("div", { className: "flex items-center space-x-2", children: [_jsx("div", { className: `w-2 h-2 rounded-full ${dept.margin > 0 ? 'bg-emerald-500' : 'bg-red-500'}` }), _jsxs("span", { className: `text-xl font-black ${dept.margin > 0 ? 'text-emerald-600' : 'text-red-600'}`, children: [dept.margin > 0 ? '+' : '', dept.margin.toFixed(1), "%"] })] })] }) })] })] })] }, dept.department)))) : (_jsx("div", { className: "col-span-2 p-6 text-center text-sm text-gray-500", children: "No department data available." })) })] })] }));
};
