import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { SearchInput } from '../../admin/SearchInput';
import { DateRangePicker } from '../../admin/DateRangePicker';
const FiltersPanel = ({ searchQuery, statusFilter, dateRange, onSearch, onStatusFilter, onDateRangeChange, statusCounts }) => {
    const statusOptions = [
        { value: 'all', label: 'All Reservations', count: statusCounts.all, color: 'bg-gray-100 text-gray-700' },
        { value: 'confirmed', label: 'Confirmed', count: statusCounts.confirmed, color: 'bg-yellow-100 text-yellow-700' },
        { value: 'checked-in', label: 'Checked In', count: statusCounts['checked-in'], color: 'bg-green-100 text-green-700' },
        { value: 'checked-out', label: 'Checked Out', count: statusCounts['checked-out'], color: 'bg-blue-100 text-blue-700' },
        { value: 'cancelled', label: 'Cancelled', count: statusCounts.cancelled || 0, color: 'bg-red-100 text-red-700' }
    ];
    return (_jsxs("div", { className: "bg-white rounded-2xl shadow-lg border border-gray-100 p-6 space-y-6 h-full", children: [_jsxs("div", { className: "flex items-center space-x-3", children: [_jsx("div", { className: "w-10 h-10 bg-gradient-to-br from-blue-500 to-indigo-600 rounded-xl flex items-center justify-center shadow-md", children: _jsx("svg", { className: "w-5 h-5 text-white", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M3 4a1 1 0 011-1h16a1 1 0 011 1v2.586a1 1 0 01-.293.707l-6.414 6.414a1 1 0 00-.293.707V17l-4 4v-6.586a1 1 0 00-.293-.707L3.293 7.207A1 1 0 013 6.5V4z" }) }) }), _jsx("h3", { className: "text-lg font-bold text-gray-900", children: "Filters & Search" })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700 mb-2", children: "Search Reservations" }), _jsx(SearchInput, { placeholder: "Search by guest name, email, or booking ID...", onSearch: onSearch })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700 mb-3", children: "Filter by Status" }), _jsx("div", { className: "grid grid-cols-2 lg:grid-cols-5 gap-2", children: statusOptions.map((option) => (_jsx("button", { onClick: () => onStatusFilter(option.value), className: `relative p-3 rounded-xl border-2 transition-all duration-300 text-left ${statusFilter === option.value
                                ? 'border-heritage-green bg-heritage-green/5 shadow-md'
                                : 'border-gray-200 hover:border-gray-300 hover:shadow-sm'}`, children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: `text-xs font-medium ${statusFilter === option.value ? 'text-heritage-green' : 'text-gray-600'}`, children: option.label }), _jsx("p", { className: `text-lg font-bold ${statusFilter === option.value ? 'text-heritage-green' : 'text-gray-900'}`, children: option.count })] }), statusFilter === option.value && (_jsx("div", { className: "w-2 h-2 bg-heritage-green rounded-full" }))] }) }, option.value))) })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700 mb-2", children: "Filter by Date Range" }), _jsx(DateRangePicker, { value: dateRange, onChange: onDateRangeChange })] }), (searchQuery || statusFilter !== 'all' || dateRange.startDate || dateRange.endDate) && (_jsxs("div", { className: "pt-4 border-t border-gray-200", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("p", { className: "text-sm font-medium text-gray-700", children: "Active Filters:" }), _jsx("button", { onClick: () => {
                                    onSearch('');
                                    onStatusFilter('all');
                                    onDateRangeChange({ startDate: '', endDate: '' });
                                }, className: "text-sm text-heritage-green hover:text-heritage-green/80 font-medium", children: "Clear All" })] }), _jsxs("div", { className: "flex flex-wrap gap-2 mt-2", children: [searchQuery && (_jsxs("span", { className: "inline-flex items-center px-3 py-1 rounded-full text-xs font-medium bg-blue-100 text-blue-800", children: ["Search: \"", searchQuery, "\""] })), statusFilter !== 'all' && (_jsxs("span", { className: "inline-flex items-center px-3 py-1 rounded-full text-xs font-medium bg-green-100 text-green-800", children: ["Status: ", statusOptions.find(opt => opt.value === statusFilter)?.label] })), (dateRange.startDate || dateRange.endDate) && (_jsx("span", { className: "inline-flex items-center px-3 py-1 rounded-full text-xs font-medium bg-purple-100 text-purple-800", children: "Date Range Applied" }))] })] }))] }));
};
export default FiltersPanel;
