import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
export const AmenitiesSection = ({ amenities }) => {
    const [isVisible, setIsVisible] = useState(false);
    const sectionRef = useRef(null);
    const navigate = useNavigate();
    useEffect(() => {
        const observer = new IntersectionObserver(([entry]) => {
            if (entry.isIntersecting) {
                setIsVisible(true);
            }
        }, { threshold: 0.1 });
        if (sectionRef.current) {
            observer.observe(sectionRef.current);
        }
        return () => observer.disconnect();
    }, []);
    return (_jsxs("section", { ref: sectionRef, className: "w-full py-10 sm:py-12 md:py-16 bg-gradient-to-br from-white via-heritage-light/10 to-white relative overflow-hidden", children: [_jsx("div", { className: "absolute top-10 left-10 w-72 h-72 bg-heritage-green/5 rounded-full blur-3xl animate-pulse" }), _jsx("div", { className: "absolute bottom-10 right-10 w-96 h-96 bg-heritage-neutral/5 rounded-full blur-3xl animate-pulse delay-1000" }), _jsxs("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10", children: [_jsxs("div", { className: `text-center mb-8 sm:mb-10 transition-all duration-1000 ${isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}`, children: [_jsx("div", { className: "inline-block mb-4 sm:mb-6 animate-bounce", children: _jsx("span", { className: "px-4 sm:px-6 py-2 sm:py-3 bg-heritage-green/10 text-heritage-green text-sm sm:text-base md:text-lg font-medium rounded-full border border-heritage-green/20 shadow-lg backdrop-blur-sm", children: "Hotel Features" }) }), _jsxs("h2", { className: "text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-bold text-gray-900 mb-3 sm:mb-4 px-4", children: ["Premium ", _jsx("span", { className: "bg-gradient-to-r from-heritage-green via-heritage-neutral to-heritage-green bg-clip-text text-transparent animate-pulse", children: "Amenities" })] }), _jsx("p", { className: "text-base sm:text-lg md:text-xl text-gray-600 max-w-3xl mx-auto px-4", children: "Experience world-class facilities designed to make your stay unforgettable" })] }), _jsx("div", { className: "grid grid-cols-1 xs:grid-cols-2 lg:grid-cols-5 gap-4 sm:gap-6 md:gap-8", children: amenities.map(({ icon: Icon, name, description }, index) => {
                            const IconComponent = Icon;
                            return (_jsxs("div", { className: `group text-center p-4 sm:p-5 md:p-6 rounded-2xl bg-gradient-to-br from-white to-heritage-light/20 hover:from-heritage-green/5 hover:to-heritage-neutral/10 border border-heritage-light/30 hover:border-heritage-green/30 transition-all duration-500 hover:shadow-2xl active:scale-95 sm:hover:-translate-y-4 transform ${isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}`, style: { transitionDelay: `${index * 100}ms` }, children: [_jsx("div", { className: "w-16 h-16 sm:w-18 sm:h-18 md:w-20 md:h-20 mx-auto mb-4 sm:mb-5 md:mb-6 bg-gradient-to-br from-heritage-green/10 to-heritage-neutral/10 rounded-full flex items-center justify-center group-hover:bg-gradient-to-br group-hover:from-heritage-green group-hover:to-heritage-neutral sm:group-hover:scale-125 sm:group-hover:rotate-12 transition-all duration-500 shadow-lg", children: _jsx(IconComponent, { className: "w-8 h-8 sm:w-9 sm:h-9 md:w-10 md:h-10 text-heritage-green group-hover:text-white transition-all duration-300" }) }), _jsx("h3", { className: "text-base sm:text-lg md:text-xl font-bold text-gray-900 mb-2 sm:mb-3 group-hover:text-heritage-green transition-colors duration-300", children: name }), _jsx("p", { className: "text-sm sm:text-base text-gray-600 leading-relaxed group-hover:text-gray-700 transition-colors duration-300", children: description }), _jsx("div", { className: "absolute top-2 right-2 w-2 h-2 bg-heritage-light rounded-full opacity-0 group-hover:opacity-100 transition-opacity duration-300" }), _jsx("div", { className: "absolute bottom-2 left-2 w-1 h-1 bg-heritage-neutral rounded-full opacity-0 group-hover:opacity-100 transition-opacity duration-300 delay-100" })] }, name));
                        }) }), _jsxs("div", { className: `text-center mt-8 sm:mt-10 px-4 transition-all duration-1000 delay-500 ${isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}`, children: [_jsx("p", { className: "text-base sm:text-lg text-gray-600 mb-4 sm:mb-6", children: "Discover more about our exceptional facilities and services" }), _jsxs("button", { onClick: () => navigate('/amenities'), className: "group relative px-8 sm:px-10 py-3 sm:py-4 md:py-5 bg-gradient-to-r from-heritage-green to-heritage-neutral hover:from-heritage-neutral hover:to-heritage-green text-white text-sm sm:text-base font-semibold rounded-full transition-all duration-500 hover:shadow-2xl hover:shadow-heritage-green/25 active:scale-95 sm:hover:scale-110 overflow-hidden", children: [_jsx("span", { className: "relative z-10", children: "View All Amenities" }), _jsx("div", { className: "absolute inset-0 bg-white/20 transform scale-x-0 group-hover:scale-x-100 transition-transform duration-500 origin-center" })] })] })] })] }));
};
