import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export const Skeleton = ({ className = '' }) => {
    return (_jsx("div", { className: `animate-pulse bg-gradient-to-r from-gray-200 via-gray-300 to-gray-200 bg-[length:200%_100%] rounded ${className}` }));
};
export const SkeletonCard = () => {
    return (_jsxs("div", { className: "overflow-hidden relative bg-white/95 backdrop-blur-2xl rounded-3xl border-white/60 shadow-2xl", children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-br from-heritage-green/8 via-heritage-light/30 to-heritage-green/5 rounded-3xl opacity-60" }), _jsxs("div", { className: "relative z-10", children: [_jsx("div", { className: "px-8 py-7 border-b bg-gradient-to-r from-white via-slate-50/80 to-white border-gray-200/30", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center space-x-5", children: [_jsx(Skeleton, { className: "w-12 h-12 rounded-2xl" }), _jsxs("div", { children: [_jsx(Skeleton, { className: "h-8 w-48 mb-2" }), _jsx(Skeleton, { className: "h-4 w-64" })] })] }), _jsx(Skeleton, { className: "h-10 w-32 rounded-2xl" })] }) }), _jsxs("div", { className: "px-8 py-6", children: [_jsx("div", { className: "space-y-4", children: [...Array(4)].map((_, index) => (_jsx("div", { className: "bg-white/80 backdrop-blur-sm p-4 rounded-xl border border-gray-200/50", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-4", children: [_jsx(Skeleton, { className: "w-12 h-12 rounded-xl" }), _jsxs("div", { children: [_jsx(Skeleton, { className: "h-5 w-32 mb-2" }), _jsx(Skeleton, { className: "h-4 w-48" })] })] }), _jsxs("div", { className: "text-right", children: [_jsx(Skeleton, { className: "h-6 w-20 mb-1" }), _jsx(Skeleton, { className: "h-4 w-16" })] })] }) }, index))) }), _jsx("div", { className: "mt-6 text-center", children: _jsx(Skeleton, { className: "h-12 w-40 rounded-2xl mx-auto" }) })] })] })] }));
};
export const SkeletonChart = () => {
    return (_jsxs("div", { className: "overflow-hidden relative bg-white/95 backdrop-blur-2xl rounded-3xl border-white/60 shadow-2xl", children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-br from-heritage-green/8 via-heritage-light/30 to-heritage-green/5 rounded-3xl opacity-60" }), _jsxs("div", { className: "relative z-10", children: [_jsx("div", { className: "px-8 py-7 border-b bg-gradient-to-r from-white via-slate-50/80 to-white border-gray-200/30", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center space-x-5", children: [_jsx(Skeleton, { className: "w-12 h-12 rounded-2xl" }), _jsxs("div", { children: [_jsx(Skeleton, { className: "h-8 w-48 mb-2" }), _jsx(Skeleton, { className: "h-4 w-64" })] })] }), _jsxs("div", { className: "flex p-1.5 bg-gradient-to-r from-heritage-light/40 to-heritage-light/60 rounded-2xl", children: [_jsx(Skeleton, { className: "h-10 w-20 rounded-xl mr-1" }), _jsx(Skeleton, { className: "h-10 w-20 rounded-xl mr-1" }), _jsx(Skeleton, { className: "h-10 w-20 rounded-xl" })] })] }) }), _jsxs("div", { className: "px-8 py-6", children: [_jsx("div", { className: "grid grid-cols-1 md:grid-cols-4 gap-6 mb-8", children: [...Array(4)].map((_, index) => (_jsxs("div", { className: "bg-white/80 backdrop-blur-sm p-6 rounded-2xl border border-gray-200/50", children: [_jsx(Skeleton, { className: "h-5 w-24 mb-3" }), _jsx(Skeleton, { className: "h-8 w-20 mb-2" }), _jsx(Skeleton, { className: "h-4 w-16" })] }, index))) }), _jsxs("div", { className: "bg-white/80 backdrop-blur-sm p-6 rounded-2xl border border-gray-200/50", children: [_jsx(Skeleton, { className: "h-6 w-32 mb-4" }), _jsx(Skeleton, { className: "h-64 w-full rounded-lg" })] })] })] })] }));
};
export const SkeletonMetrics = () => {
    return (_jsxs("div", { className: "overflow-hidden relative bg-white/95 backdrop-blur-2xl rounded-3xl border-white/60 shadow-2xl", children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-br from-heritage-green/8 via-heritage-light/30 to-heritage-green/5 rounded-3xl opacity-60" }), _jsxs("div", { className: "relative z-10", children: [_jsx("div", { className: "px-8 py-7 border-b bg-gradient-to-r from-white via-slate-50/80 to-white border-gray-200/30", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center space-x-5", children: [_jsx(Skeleton, { className: "w-12 h-12 rounded-2xl" }), _jsxs("div", { children: [_jsx(Skeleton, { className: "h-8 w-40 mb-2" }), _jsx(Skeleton, { className: "h-4 w-56" })] })] }), _jsx(Skeleton, { className: "h-12 w-32 rounded-2xl" })] }) }), _jsxs("div", { className: "px-8 py-6", children: [_jsx("div", { className: "grid grid-cols-1 md:grid-cols-4 gap-6 mb-6", children: [...Array(4)].map((_, index) => (_jsxs("div", { className: "bg-white/80 backdrop-blur-sm p-6 rounded-2xl border border-gray-200/50", children: [_jsx(Skeleton, { className: "h-5 w-24 mb-3" }), _jsx(Skeleton, { className: "h-10 w-28 mb-2" }), _jsx(Skeleton, { className: "h-4 w-20" })] }, index))) }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6", children: [...Array(4)].map((_, index) => (_jsxs("div", { className: "bg-white/80 backdrop-blur-sm p-6 rounded-2xl border border-gray-200/50", children: [_jsxs("div", { className: "flex items-center gap-3 mb-4", children: [_jsx(Skeleton, { className: "w-8 h-8 rounded-lg" }), _jsx(Skeleton, { className: "h-5 w-32" })] }), _jsx(Skeleton, { className: "h-4 w-full mb-2" }), _jsx(Skeleton, { className: "h-4 w-3/4" })] }, index))) })] })] })] }));
};
