import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState, useMemo } from 'react';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { getRevenueData, calculateChartMetrics, formatCurrency, formatShortCurrency } from './chartsLogic/revenueAnalyticsLogic';
// Custom tooltip component with proper typing
const CustomTooltip = ({ active, payload, label }) => {
    if (active && payload && payload.length) {
        return (_jsxs("div", { className: "bg-white/95 backdrop-blur-sm border border-gray-200 rounded-lg shadow-lg p-4 min-w-[200px]", children: [_jsx("p", { className: "mb-2 font-medium text-gray-900", children: label }), payload.map((entry, index) => (_jsxs("div", { className: "flex items-center justify-between gap-4 mb-1", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "w-3 h-3 rounded-full", style: { backgroundColor: entry.color } }), _jsx("span", { className: "text-sm text-gray-600 capitalize", children: entry.dataKey })] }), _jsx("span", { className: "text-sm font-medium text-gray-900", children: formatCurrency(entry.value) })] }, `tooltip-${String(index)}`)))] }));
    }
    return null;
};
// Recharts aliases to avoid JSX typing conflicts
const RResponsiveContainer = ResponsiveContainer;
const RAreaChart = AreaChart;
const RXAxis = XAxis;
const RYAxis = YAxis;
const RCartesianGrid = CartesianGrid;
const RTooltip = Tooltip;
const RArea = Area;
const RevenueAnalytics = () => {
    const [activeTimeframe, setActiveTimeframe] = useState('weekly');
    // Get data and metrics
    const revenueData = useMemo(() => getRevenueData(activeTimeframe), [activeTimeframe]);
    const metrics = useMemo(() => calculateChartMetrics(revenueData), [revenueData]);
    // Transform data for recharts
    const chartData = revenueData.map((item) => ({
        day: item.day,
        revenue: item.revenue
    }));
    return (_jsxs("div", { className: "relative overflow-hidden shadow-2xl bg-white/95 backdrop-blur-2xl rounded-3xl border-white/60 animate-fade-in", children: [_jsx("div", { className: "absolute inset-0 transition-opacity duration-700 bg-gradient-to-br from-heritage-green/8 via-heritage-light/30 to-heritage-green/5 rounded-3xl opacity-60 group-hover:opacity-100" }), _jsxs("div", { className: "relative z-10", children: [_jsx("div", { className: "px-8 border-b py-7 bg-gradient-to-r from-white via-slate-50/80 to-white border-gray-200/30", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center space-x-5", children: [_jsxs("div", { className: "relative group", children: [_jsx("div", { className: "p-2 bg-[#82A33D]/10 rounded-xl", children: _jsx("svg", { className: "w-6 h-6 text-[#82A33D]", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" }) }) }), _jsx("div", { className: "absolute transition-opacity duration-300 -inset-2 bg-gradient-to-r from-heritage-green/20 to-heritage-neutral/20 rounded-2xl blur-xl opacity-60 group-hover:opacity-100" })] }), _jsxs("div", { children: [_jsx("h3", { className: "text-2xl font-black text-transparent bg-gradient-to-r from-gray-900 via-gray-800 to-gray-900 bg-clip-text", children: "Revenue Analytics" }), _jsxs("div", { className: "flex items-center gap-2 mt-1", children: [_jsx("p", { className: "text-sm font-semibold text-gray-600", children: "Performance Metrics" }), _jsx("div", { className: "w-1 h-1 rounded-full bg-heritage-green" }), _jsx("span", { className: "text-sm font-bold text-heritage-green", children: "October 2025" })] })] })] }), _jsx("div", { className: "flex space-x-4", children: _jsxs("div", { className: "flex p-1.5 bg-gradient-to-r from-heritage-light/40 to-heritage-light/60 rounded-2xl shadow-inner backdrop-blur-sm border border-heritage-light/30", children: [_jsx("button", { className: `px-5 py-2.5 text-sm font-bold rounded-xl transition-all duration-300 ${activeTimeframe === 'weekly'
                                                    ? 'text-white bg-gradient-to-r from-heritage-green to-heritage-neutral shadow-lg transform scale-105'
                                                    : 'text-gray-700 hover:text-heritage-green hover:bg-white/50'}`, onClick: () => setActiveTimeframe('weekly'), children: "Weekly" }), _jsx("button", { className: `px-5 py-2.5 text-sm font-bold rounded-xl transition-all duration-300 ${activeTimeframe === 'monthly'
                                                    ? 'text-white bg-gradient-to-r from-heritage-green to-heritage-neutral shadow-lg transform scale-105'
                                                    : 'text-gray-700 hover:text-heritage-green hover:bg-white/50'}`, onClick: () => setActiveTimeframe('monthly'), children: "Monthly" }), _jsx("button", { className: `px-5 py-2.5 text-sm font-bold rounded-xl transition-all duration-300 ${activeTimeframe === 'yearly'
                                                    ? 'text-white bg-gradient-to-r from-heritage-green to-heritage-neutral shadow-lg transform scale-105'
                                                    : 'text-gray-700 hover:text-heritage-green hover:bg-white/50'}`, onClick: () => setActiveTimeframe('yearly'), children: "Yearly" })] }) })] }) }), _jsxs("div", { className: "px-4 py-6", children: [_jsx("div", { className: "h-[320px] w-full", children: _jsx(RResponsiveContainer, { width: "100%", height: "100%", children: _jsxs(RAreaChart, { data: chartData, margin: { top: 20, right: 10, left: 10, bottom: 20 }, children: [_jsx("defs", { children: _jsxs("linearGradient", { id: "colorRevenue", x1: "0", y1: "0", x2: "0", y2: "1", children: [_jsx("stop", { offset: "5%", stopColor: "#82A33D", stopOpacity: 0.8 }), _jsx("stop", { offset: "95%", stopColor: "#ABAD8A", stopOpacity: 0.1 })] }) }), _jsx(RXAxis, { dataKey: "day", tick: { fill: '#82A33D', fontSize: 12 }, axisLine: { stroke: '#82A33D', strokeWidth: 1 }, tickLine: false, interval: 0, padding: { left: 0, right: 0 } }), _jsx(RYAxis, { tickFormatter: formatShortCurrency, tick: { fill: '#82A33D', fontSize: 12 }, axisLine: false, tickLine: false }), _jsx(RCartesianGrid, { strokeDasharray: "3 3", vertical: false, stroke: "#ABAD8A" }), _jsx(RTooltip, { content: _jsx(CustomTooltip, {}) }), _jsx(RArea, { type: "linear", dataKey: "revenue", stroke: "#82A33D", fillOpacity: 1, fill: "url(#colorRevenue)", strokeWidth: 3, connectNulls: true, dot: false, activeDot: {
                                                    r: 6,
                                                    stroke: '#ABAD8A',
                                                    strokeWidth: 2,
                                                    fill: 'white'
                                                } })] }) }) }), _jsx("div", { className: "flex items-center justify-center pb-2 mt-2", children: _jsxs("div", { className: "flex items-center gap-2 text-xs text-gray-600", children: [_jsx("div", { className: "w-3 h-0.5 bg-heritage-green rounded" }), _jsx("span", { children: "Daily Revenue" })] }) })] }), _jsxs("div", { className: "grid grid-cols-1 gap-4 px-8 py-6 sm:grid-cols-2 md:grid-cols-4", children: [_jsxs("div", { className: "p-4 border shadow-sm bg-white/80 rounded-xl border-heritage-light", children: [_jsx("div", { className: "text-sm font-medium text-gray-500", children: "Total Revenue" }), _jsx("div", { className: "text-2xl font-bold text-heritage-green", children: formatCurrency(metrics?.totalRevenue || 85800) }), _jsxs("div", { className: "flex items-center gap-1 mt-1 text-xs font-medium text-emerald-600", children: [_jsx("svg", { className: "w-3 h-3", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M5 10l7-7m0 0l7 7m-7-7v18" }) }), _jsxs("span", { children: [metrics?.growthRate || 4, "%"] })] })] }), _jsxs("div", { className: "p-4 border shadow-sm bg-white/80 rounded-xl border-heritage-light", children: [_jsx("div", { className: "text-sm font-medium text-gray-500", children: "Average" }), _jsx("div", { className: "text-2xl font-bold text-heritage-green", children: formatCurrency(metrics?.averageRevenue || 12257) }), _jsx("div", { className: "text-xs text-gray-500", children: "Per day" })] }), _jsxs("div", { className: "p-4 border shadow-sm bg-white/80 rounded-xl border-heritage-light", children: [_jsx("div", { className: "text-sm font-medium text-gray-500", children: "Highest Day" }), _jsx("div", { className: "text-2xl font-bold text-heritage-green", children: formatCurrency(metrics?.maxRevenue || 15400) }), _jsx("div", { className: "text-xs text-gray-500", children: metrics?.maxDay || "Friday" })] }), _jsxs("div", { className: "p-4 border shadow-sm bg-white/80 rounded-xl border-heritage-light", children: [_jsx("div", { className: "text-sm font-medium text-gray-500", children: "Projected" }), _jsx("div", { className: "text-2xl font-bold text-heritage-green", children: formatCurrency(metrics?.projectedRevenue || 92500) }), _jsx("div", { className: "text-xs text-gray-500", children: "Next week" })] })] })] })] }));
};
export default RevenueAnalytics;
