import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const ScheduleHeader = () => {
    return (_jsxs("div", { className: "relative bg-gradient-to-br from-white via-green-50/20 to-green-500/5 rounded-3xl shadow-2xl border border-green-500/10 overflow-hidden mb-8", children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-br from-green-500/5 via-transparent to-green-600/5" }), _jsx("div", { className: "absolute top-0 right-0 w-96 h-96 bg-gradient-to-bl from-green-500/10 to-transparent rounded-full -translate-y-1/2 translate-x-1/2 animate-pulse" }), _jsx("div", { className: "absolute bottom-0 left-0 w-80 h-80 bg-gradient-to-tr from-green-100/15 to-transparent rounded-full translate-y-1/2 -translate-x-1/2 animate-pulse delay-1000" }), _jsx("div", { className: "relative p-10", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsx("div", { className: "space-y-4", children: _jsxs("div", { className: "flex items-center space-x-4", children: [_jsxs("div", { className: "relative group", children: [_jsx("div", { className: "w-16 h-16 bg-gradient-to-br from-[#82A33D] to-[#6d8a33] rounded-2xl flex items-center justify-center shadow-xl border border-[#82A33D]/30 group-hover:scale-110 transition-all duration-500", children: _jsx("svg", { className: "w-8 h-8 text-white drop-shadow-lg", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" }) }) }), _jsx("div", { className: "absolute -inset-1 bg-gradient-to-r from-[#82A33D] to-green-400 rounded-2xl blur opacity-30 group-hover:opacity-50 transition duration-500" })] }), _jsxs("div", { className: "space-y-2", children: [_jsx("h1", { className: "text-5xl font-black text-[#82A33D] drop-shadow-sm", children: "Staff Schedules" }), _jsx("p", { className: "text-xl text-gray-700 font-medium tracking-wide", children: "Schedule and manage staff shifts" }), _jsxs("div", { className: "flex items-center space-x-4 mt-4", children: [_jsxs("div", { className: "flex items-center space-x-2 bg-emerald-50 backdrop-blur-sm rounded-full px-4 py-2 border border-emerald-200", children: [_jsx("div", { className: "w-2 h-2 bg-emerald-500 rounded-full animate-pulse" }), _jsx("span", { className: "text-sm font-semibold text-emerald-700", children: "All systems operational" })] }), _jsxs("div", { className: "flex items-center space-x-2 bg-blue-50 backdrop-blur-sm rounded-full px-4 py-2 border border-blue-200", children: [_jsx("svg", { className: "w-4 h-4 text-blue-600", fill: "currentColor", viewBox: "0 0 20 20", children: _jsx("path", { fillRule: "evenodd", d: "M10 18a8 8 0 100-16 8 8 0 000 16zm1-12a1 1 0 10-2 0v4a1 1 0 00.293.707l2.828 2.829a1 1 0 101.415-1.415L11 9.586V6z", clipRule: "evenodd" }) }), _jsx("span", { className: "text-sm font-medium text-blue-700", children: new Date().toLocaleDateString("en-US", {
                                                                    weekday: "long",
                                                                    month: "short",
                                                                    day: "numeric",
                                                                }) })] })] })] })] }) }), _jsx("div", { className: "text-right", children: _jsx("div", { className: "relative group", children: _jsxs("div", { className: "bg-gradient-to-br from-white/90 to-green-500/5 backdrop-blur-xl rounded-3xl p-8 border border-green-500/20 shadow-xl group-hover:scale-105 transition-all duration-500", children: [_jsx("div", { className: "absolute -inset-1 bg-gradient-to-r from-[#82A33D] to-green-400 rounded-3xl blur opacity-20 group-hover:opacity-40 transition duration-500" }), _jsxs("div", { className: "relative", children: [_jsx("p", { className: "text-4xl font-black bg-gradient-to-r from-[#82A33D] to-green-600 bg-clip-text text-transparent drop-shadow-sm", children: new Date().toLocaleTimeString("en-US", {
                                                        hour: "2-digit",
                                                        minute: "2-digit",
                                                    }) }), _jsx("p", { className: "text-gray-700 mt-2 font-semibold tracking-wide", children: "Current Time" }), _jsxs("div", { className: "mt-3 flex items-center justify-center space-x-2", children: [_jsx("div", { className: "w-1 h-1 bg-[#82A33D] rounded-full animate-ping" }), _jsx("div", { className: "w-1 h-1 bg-green-600 rounded-full animate-ping delay-75" }), _jsx("div", { className: "w-1 h-1 bg-green-400 rounded-full animate-ping delay-150" })] })] })] }) }) })] }) })] }));
};
export default ScheduleHeader;
