export const expenses = [
    {
        id: 'EXP-2024-001',
        description: 'Monthly electricity bill',
        category: 'utilities',
        amount: 2450.0,
        vendor: 'City Power Company',
        date: '2024-10-05',
        status: 'approved',
        submittedBy: 'John Manager',
        approvedBy: 'Sarah Director',
        receiptUrl: '/receipts/exp-001.pdf',
        notes: 'Higher than usual due to increased AC usage',
    },
    {
        id: 'EXP-2024-002',
        description: 'Cleaning supplies and chemicals',
        category: 'supplies',
        amount: 850.5,
        vendor: 'CleanCorp Supplies',
        date: '2024-10-06',
        status: 'pending',
        submittedBy: 'Mike Housekeeping',
        notes: 'Monthly stock replenishment',
    },
    {
        id: 'EXP-2024-003',
        description: 'HVAC system maintenance',
        category: 'maintenance',
        amount: 1200.0,
        vendor: 'TechFix Solutions',
        date: '2024-10-07',
        status: 'pending',
        submittedBy: 'Tom Maintenance',
        notes: 'Quarterly maintenance check',
    },
    {
        id: 'EXP-2024-004',
        description: 'Social media advertising',
        category: 'marketing',
        amount: 500.0,
        vendor: 'Digital Marketing Pro',
        date: '2024-10-08',
        status: 'rejected',
        submittedBy: 'Lisa Marketing',
        notes: 'Rejected - needs budget approval first',
    },
    {
        id: 'EXP-2024-005',
        description: 'Fresh produce delivery',
        category: 'food',
        amount: 1850.75,
        vendor: 'Farm Fresh Suppliers',
        date: '2024-10-08',
        status: 'paid',
        submittedBy: 'Chef Robert',
        approvedBy: 'Sarah Director',
        notes: 'Weekly fresh produce order',
    },
];
