import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ExpenseModal } from './ExpenseModal';
const SuccessModal = ({ isOpen, onClose, title = 'Success', message = 'Operation completed successfully.', cta = null }) => {
    return (_jsx(ExpenseModal, { isOpen: isOpen, onClose: onClose, children: _jsxs("div", { className: "space-y-6 max-w-md mx-auto", children: [_jsxs("div", { className: "flex items-start justify-between", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "flex items-center justify-center w-10 h-10 text-white rounded-full shadow-sm bg-emerald-600", children: _jsx("svg", { className: "w-5 h-5", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M5 13l4 4L19 7" }) }) }), _jsxs("div", { children: [_jsx("h3", { className: "text-lg font-semibold text-emerald-700", children: title }), _jsx("p", { className: "mt-1 text-sm text-gray-600", children: message })] })] }), _jsx("button", { type: "button", onClick: onClose, "aria-label": "Close", className: "inline-flex items-center justify-center w-8 h-8 text-emerald-700 bg-emerald-50 rounded-md ring-1 ring-emerald-100", children: _jsx("svg", { className: "w-4 h-4", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M6 18L18 6M6 6l12 12" }) }) })] }), _jsxs("div", { className: "flex items-center justify-center gap-3 pt-4 border-t border-gray-100", children: [cta ? (_jsx("button", { type: "button", onClick: () => {
                                cta.onClick();
                                onClose();
                            }, className: "px-4 py-2 text-sm font-semibold text-white rounded-lg shadow-md bg-gradient-to-r from-[#82A33D] to-emerald-600 hover:from-[#6d8735] hover:to-emerald-700", children: cta.label })) : null, _jsx("button", { type: "button", onClick: onClose, className: "px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-200 rounded-lg hover:bg-gray-100", children: "Close" })] })] }) }));
};
export default SuccessModal;
