import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from 'react';
export const FilterDropdown = ({ value, onChange, options, placeholder = "Select option", className = "" }) => {
    const [isOpen, setIsOpen] = useState(false);
    const selectedOption = options.find(option => option.value === value);
    return (_jsxs("div", { className: `relative ${className}`, children: [_jsxs("button", { onClick: () => setIsOpen(!isOpen), className: "w-full px-4 py-2.5 bg-white border border-gray-300 rounded-lg shadow-sm hover:border-gray-400 focus:outline-none focus:ring-2 focus:ring-heritage-green focus:border-heritage-green transition-all duration-200 flex items-center justify-between text-sm", children: [_jsxs("div", { className: "flex items-center gap-2", children: [selectedOption?.icon && (_jsx("span", { className: "text-sm", children: selectedOption.icon })), _jsx("span", { className: selectedOption ? "text-gray-900" : "text-gray-500", children: selectedOption ? selectedOption.label : placeholder })] }), _jsx("svg", { className: `w-4 h-4 text-gray-400 transition-transform duration-200 ${isOpen ? 'rotate-180' : ''}`, fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M19 9l-7 7-7-7" }) })] }), isOpen && (_jsxs(_Fragment, { children: [_jsx("div", { className: "fixed inset-0 z-10", onClick: () => setIsOpen(false) }), _jsx("div", { className: "absolute z-20 w-full mt-1 bg-white border border-gray-200 rounded-lg shadow-lg max-h-60 overflow-auto", children: options.map((option) => (_jsxs("button", { onClick: () => {
                                onChange(option.value);
                                setIsOpen(false);
                            }, className: `w-full px-4 py-3 text-left hover:bg-gray-50 focus:bg-gray-50 focus:outline-none transition-colors duration-150 flex items-center gap-3 text-sm border-b border-gray-100 last:border-b-0 ${value === option.value
                                ? 'bg-heritage-green/5 text-heritage-green font-medium'
                                : 'text-gray-700'}`, children: [option.icon && (_jsx("span", { className: "text-sm flex-shrink-0", children: option.icon })), _jsx("span", { className: "flex-1", children: option.label }), value === option.value && (_jsx("svg", { className: "w-4 h-4 text-heritage-green flex-shrink-0", fill: "currentColor", viewBox: "0 0 20 20", children: _jsx("path", { fillRule: "evenodd", d: "M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z", clipRule: "evenodd" }) }))] }, option.value))) })] }))] }));
};
