import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Search, ChevronDown } from 'lucide-react';
import { FAQS_DATA, FAQ_CATEGORIES } from '../../../data/faqsData';
export const FaqsTab = () => {
    const [activeId, setActiveId] = useState(null);
    const [searchQuery, setSearchQuery] = useState('');
    const [activeCategory, setActiveCategory] = useState('All');
    const faqs = FAQS_DATA;
    const categories = FAQ_CATEGORIES;
    const filteredFaqs = faqs.filter(faq => {
        const matchesSearch = faq.question.toLowerCase().includes(searchQuery.toLowerCase()) ||
            faq.answer.toLowerCase().includes(searchQuery.toLowerCase());
        const matchesCategory = activeCategory === 'All' || faq.category === activeCategory;
        return matchesSearch && matchesCategory;
    });
    const toggleFAQ = (id) => {
        setActiveId(activeId === id ? null : id);
    };
    return (_jsxs("div", { className: "space-y-8", children: [_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "relative group", children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-r from-heritage-green/20 to-heritage-neutral/20 rounded-2xl blur-xl opacity-0 group-hover:opacity-100 transition-opacity duration-500" }), _jsx("div", { className: "relative bg-white rounded-2xl shadow-lg border border-gray-100 overflow-hidden hover:shadow-xl transition-shadow duration-300", children: _jsxs("div", { className: "flex items-center gap-4 p-2", children: [_jsx("div", { className: "flex items-center justify-center w-12 h-12 rounded-xl bg-heritage-green/10 ml-2", children: _jsx(Search, { className: "w-5 h-5 text-heritage-green" }) }), _jsx("input", { type: "text", placeholder: "Ask a question or search keywords...", value: searchQuery, onChange: (e) => setSearchQuery(e.target.value), className: "flex-1 py-3 pr-6 text-gray-800 bg-transparent focus:outline-none placeholder:text-gray-400 text-base" }), searchQuery && (_jsx("button", { onClick: () => setSearchQuery(''), className: "mr-4 text-gray-400 hover:text-heritage-green transition-colors", children: _jsx("span", { className: "text-sm font-medium", children: "Clear" }) }))] }) })] }), searchQuery && (_jsxs("div", { className: "flex items-center gap-2 text-sm text-gray-600 animate-fadeIn", children: [_jsx("div", { className: "w-1.5 h-1.5 bg-heritage-green rounded-full" }), _jsxs("span", { children: ["Found ", _jsx("strong", { className: "text-heritage-green", children: filteredFaqs.length }), " ", filteredFaqs.length === 1 ? 'result' : 'results'] })] }))] }), _jsxs("div", { children: [_jsx("h3", { className: "text-sm font-semibold text-gray-500 uppercase tracking-wider mb-4", children: "Filter by Category" }), _jsx("div", { className: "flex flex-wrap gap-3", children: categories.map(category => {
                            const count = category === 'All'
                                ? faqs.length
                                : faqs.filter(faq => faq.category === category).length;
                            return (_jsx("button", { onClick: () => setActiveCategory(category), className: `group relative px-6 py-3 rounded-xl font-semibold text-sm transition-all duration-300 ${activeCategory === category
                                    ? 'bg-gradient-to-r from-heritage-green to-heritage-neutral text-white shadow-lg shadow-heritage-green/30'
                                    : 'bg-white text-gray-700 hover:text-heritage-green hover:bg-heritage-green/5 border-2 border-gray-200 hover:border-heritage-green/40 hover:shadow-md'}`, children: _jsxs("span", { className: "flex items-center gap-2", children: [category, _jsx("span", { className: `inline-flex items-center justify-center min-w-[24px] h-6 px-2 rounded-full text-xs font-bold ${activeCategory === category
                                                ? 'bg-white/20 text-white'
                                                : 'bg-gray-100 text-gray-600 group-hover:bg-heritage-green/10 group-hover:text-heritage-green'}`, children: count })] }) }, category));
                        }) })] }), _jsx("div", { className: "space-y-4", children: filteredFaqs.length === 0 ? (_jsxs("div", { className: "text-center py-16 bg-white rounded-2xl border-2 border-dashed border-gray-200", children: [_jsx("div", { className: "inline-flex items-center justify-center w-16 h-16 mb-4 rounded-full bg-gray-100", children: _jsx(Search, { className: "w-8 h-8 text-gray-400" }) }), _jsx("h3", { className: "text-lg font-semibold text-gray-900 mb-2", children: "No results found" }), _jsx("p", { className: "text-gray-500", children: "Try adjusting your search or filter to find what you're looking for." })] })) : (filteredFaqs.map((faq, index) => (_jsxs("div", { className: "group bg-white rounded-2xl shadow-md border-2 border-gray-100 overflow-hidden transition-all duration-300 hover:shadow-2xl hover:border-heritage-green/40 hover:-translate-y-1", style: { animationDelay: `${index * 50}ms` }, children: [_jsxs("button", { onClick: () => toggleFAQ(faq.id), className: "flex items-start justify-between w-full p-6 text-left transition-all duration-200", children: [_jsxs("div", { className: "flex-1 pr-4", children: [_jsxs("div", { className: "flex items-center gap-3 mb-3", children: [_jsx("span", { className: "inline-flex items-center px-3 py-1.5 text-xs font-bold rounded-full bg-heritage-green/10 text-heritage-green border border-heritage-green/20 group-hover:bg-heritage-green/20 transition-colors", children: faq.category }), activeId === faq.id && (_jsx("span", { className: "inline-flex items-center px-2 py-1 text-xs font-semibold text-heritage-green animate-fadeIn", children: "\u25CF Reading" }))] }), _jsx("h3", { className: "text-lg font-bold text-gray-900 group-hover:text-heritage-green transition-colors leading-relaxed", children: faq.question })] }), _jsx("div", { className: `flex-shrink-0 w-11 h-11 flex items-center justify-center rounded-xl transition-all duration-300 ${activeId === faq.id
                                        ? 'bg-gradient-to-br from-heritage-green to-heritage-neutral text-white shadow-lg shadow-heritage-green/40 rotate-180'
                                        : 'bg-gray-50 text-gray-400 group-hover:bg-heritage-green/10 group-hover:text-heritage-green group-hover:scale-110'}`, children: _jsx(ChevronDown, { className: "w-5 h-5" }) })] }), _jsx("div", { className: `transition-all duration-500 ease-in-out ${activeId === faq.id
                                ? 'max-h-96 opacity-100'
                                : 'max-h-0 opacity-0'} overflow-hidden`, children: _jsx("div", { className: "px-6 pb-6", children: _jsx("div", { className: "pt-4 border-t-2 border-gray-100", children: _jsxs("div", { className: "flex gap-3", children: [_jsx("div", { className: "flex-shrink-0 w-1 bg-gradient-to-b from-heritage-green to-heritage-neutral rounded-full" }), _jsx("p", { className: "leading-relaxed text-gray-700 text-base", children: faq.answer })] }) }) }) })] }, faq.id)))) })] }));
};
