import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import useGetInvAnalytic from "@/api/getInvAnalytic";
import { useEffect, useState } from "react";
const TopMovingItems = ({ topMovingItems }) => {
    return (_jsxs("div", { className: "bg-gradient-to-br from-white via-white to-heritage-green/5 backdrop-blur-xl rounded-3xl p-8 shadow-2xl border border-white/60 hover:shadow-3xl hover:-translate-y-2 transition-all duration-700 group", children: [_jsxs("div", { className: "flex items-center mb-8", children: [_jsx("div", { className: "w-16 h-16 bg-gradient-to-br from-heritage-green/20 via-green-400/30 to-emerald-500/20 rounded-2xl flex items-center justify-center mr-5 shadow-lg group-hover:shadow-xl group-hover:scale-110 transition-all duration-500", children: _jsx("div", { className: "text-3xl animate-pulse", children: "\uD83D\uDCC8" }) }), _jsxs("div", { children: [_jsx("h3", { className: "text-2xl font-bold bg-gradient-to-r from-heritage-green to-emerald-600 bg-clip-text text-transparent", children: "Top Moving Items" }), _jsx("p", { className: "text-base text-gray-600 mt-1", children: "High-demand inventory trends" })] })] }), _jsx("div", { className: "space-y-4", children: topMovingItems.map((item, index) => (_jsxs("div", { className: `group/item flex items-center justify-between p-6 bg-gradient-to-r ${item.color} rounded-2xl border ${item.border} hover:shadow-lg hover:scale-[1.02] transition-all duration-300 cursor-pointer relative overflow-hidden`, children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-r from-white/20 to-transparent opacity-0 group-hover/item:opacity-100 transition-opacity duration-300" }), _jsxs("div", { className: "relative z-10", children: [_jsx("div", { className: "font-bold text-lg text-gray-900 mb-1", children: item.name }), _jsx("div", { className: "text-sm text-gray-600 font-medium", children: item.department })] }), _jsxs("div", { className: "text-right relative z-10", children: [_jsx("div", { className: "font-black text-xl text-gray-900 mb-1", children: item.units }), _jsxs("div", { className: `text-sm font-bold ${item.trendColor || "text-green-600"} flex items-center justify-end bg-white/60 px-3 py-1 rounded-full shadow-sm`, children: [_jsx("span", { className: "mr-1 text-base", children: item.trend.startsWith("-") ? "↘" : "↗" }), " ", item.trend] })] })] }, index))) })] }));
};
const CriticalStocksLevel = ({ criticalStocks, }) => {
    return (_jsxs("div", { className: "bg-gradient-to-br from-white via-white to-red-50/30 backdrop-blur-xl rounded-3xl p-8 shadow-2xl border border-white/60 hover:shadow-3xl hover:-translate-y-2 transition-all duration-700 group", children: [_jsxs("div", { className: "flex items-center mb-8", children: [_jsx("div", { className: "w-16 h-16 bg-gradient-to-br from-red-100 via-orange-200/50 to-red-200/30 rounded-2xl flex items-center justify-center mr-5 shadow-lg group-hover:shadow-xl group-hover:scale-110 transition-all duration-500", children: _jsx("div", { className: "text-3xl animate-bounce", children: "\u26A0\uFE0F" }) }), _jsxs("div", { children: [_jsx("h3", { className: "text-2xl font-bold bg-gradient-to-r from-red-600 to-orange-600 bg-clip-text text-transparent", children: "Critical Stocks Level" }), _jsx("p", { className: "text-base text-gray-600 mt-1", children: "Items requiring immediate attention" })] })] }), _jsx("div", { className: "space-y-4", children: criticalStocks.map((stock, index) => (_jsxs("div", { className: `group/item flex items-center justify-between p-6 bg-gradient-to-r ${stock.color} rounded-2xl border ${stock.border} hover:shadow-lg hover:scale-[1.02] transition-all duration-300 cursor-pointer relative overflow-hidden`, children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-r from-white/20 to-transparent opacity-0 group-hover/item:opacity-100 transition-opacity duration-300" }), _jsxs("div", { className: "relative z-10", children: [_jsx("div", { className: "font-bold text-lg text-gray-900 mb-1", children: stock.name }), _jsx("div", { className: "text-sm text-gray-600 font-medium", children: stock.department })] }), _jsx("div", { className: "text-right relative z-10", children: _jsxs("span", { className: `inline-flex items-center px-4 py-2 rounded-2xl text-sm font-bold bg-gradient-to-r ${stock.statusColor} ${stock.textColor} shadow-lg hover:shadow-xl transition-all duration-300 group-hover/item:scale-105`, children: [_jsx("span", { className: "mr-2 text-base animate-pulse", children: stock.emoji }), " ", stock.status] }) })] }, index))) })] }));
};
const WastageAnalysis = ({ wastageItems }) => {
    return (_jsxs("div", { className: "bg-gradient-to-br from-white via-white to-orange-50/30 backdrop-blur-xl rounded-3xl p-8 shadow-2xl border border-white/60 hover:shadow-3xl hover:-translate-y-2 transition-all duration-700 group", children: [_jsxs("div", { className: "flex items-center mb-8", children: [_jsx("div", { className: "w-16 h-16 bg-gradient-to-br from-orange-100 via-red-200/50 to-orange-200/30 rounded-2xl flex items-center justify-center mr-5 shadow-lg group-hover:shadow-xl group-hover:scale-110 transition-all duration-500", children: _jsx("div", { className: "text-3xl animate-pulse", children: "\uD83D\uDCCA" }) }), _jsxs("div", { children: [_jsx("h3", { className: "text-2xl font-bold bg-gradient-to-r from-orange-600 to-red-600 bg-clip-text text-transparent", children: "Wastage Analysis" }), _jsx("p", { className: "text-base text-gray-600 mt-1", children: "Cost impact assessment & trends" })] })] }), _jsxs("div", { className: "space-y-4", children: [wastageItems.map((item, index) => (_jsxs("div", { className: `group/item flex items-center justify-between p-6 bg-gradient-to-r ${item.color} rounded-2xl border ${item.border} hover:shadow-lg hover:scale-[1.02] transition-all duration-300 cursor-pointer relative overflow-hidden`, children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-r from-white/20 to-transparent opacity-0 group-hover/item:opacity-100 transition-opacity duration-300" }), _jsxs("div", { className: "relative z-10", children: [_jsx("div", { className: "font-bold text-lg text-gray-900 mb-1", children: item.name }), _jsx("div", { className: "text-sm text-gray-600 font-medium", children: item.department })] }), _jsxs("div", { className: "text-right relative z-10", children: [_jsx("div", { className: "font-black text-xl text-gray-900 mb-1", children: item.amount }), _jsx("div", { className: `text-sm font-bold ${item.textColor} bg-white/60 px-3 py-1 rounded-full shadow-sm`, children: item.percentage })] })] }, index))), _jsx("div", { className: "border-t-2 border-gradient-to-r from-gray-200 to-gray-300 pt-8 mt-8", children: _jsxs("div", { className: "flex items-center justify-between p-8 bg-gradient-to-br from-red-100 via-orange-100 to-red-200/50 rounded-3xl border-2 border-red-200/60 shadow-xl hover:shadow-2xl hover:scale-[1.02] transition-all duration-500 group/total", children: [_jsx("div", { className: "font-black text-xl text-gray-900", children: "Total This Month" }), _jsxs("div", { className: "text-right", children: [_jsx("div", { className: "text-4xl font-black bg-gradient-to-r from-red-600 to-orange-600 bg-clip-text text-transparent group-hover/total:scale-110 transition-transform duration-300", children: "\u20B126,620" }), _jsx("div", { className: "text-base font-bold text-gray-700 mt-1 bg-white/60 px-3 py-1 rounded-full shadow-sm", children: "5.3% total waste" })] })] }) })] })] }));
};
const AnalyticsBottomSections = () => {
    const [topMovingItems, setTopMovingItems] = useState([]);
    const [criticalStocks, setCriticalStocks] = useState([]);
    const [wastageItems, setWastageItems] = useState([]);
    const { getInvAnalyticsBottomSection, } = useGetInvAnalytic();
    useEffect(() => {
        const useGetInvAnalyticFunc = async () => {
            const response = await getInvAnalyticsBottomSection();
            if (!response.success) {
                alert(response.message);
                return;
            }
            console.log(response.data);
            setTopMovingItems(response.data[0]);
            setCriticalStocks(response.data[1]);
            setWastageItems(response.data[2]);
        };
        useGetInvAnalyticFunc();
    }, []);
    return (_jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-3 gap-8 lg:gap-10", children: [_jsx(TopMovingItems, { topMovingItems: topMovingItems }), _jsx(CriticalStocksLevel, { criticalStocks: criticalStocks }), _jsx(WastageAnalysis, { wastageItems: wastageItems })] }));
};
export default AnalyticsBottomSections;
